# Generated by Django 5.2.1 on 2025-10-23 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_alter_categoria_descripcion_alter_categoria_slug'),
        ('store', '0002_alter_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Category',
        ),
    ]
